[build]
  command = "npm run build"
  publish = "dist"

[context.deploy-preview]
  command = "npm run build-preview"
  
[context.production.environment]
  HUGO_VERSION = "0.30.2"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
